catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^favorite/$', views.UserFavoritesBooksListView.as_view(), name='my_favorites'),
    re_path(r'book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
    re_path(r'author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    re_path(r'author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    Model representing a book
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1500, help_text="Enter a brief description of the book")
    image = models.ImageField(upload_to='book_image', blank=True, null=True)
    isbn = models.CharField('ISBN', max_length=17, help_text="Enter a book's ISBN")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined, so we can specify the object above.
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    favorites = models.ManyToManyField(User, help_text='Choose favorite books', related_name='created', blank=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        genre = [genre.name for genre in self.genre.all()[:3]]
        if len(genre) >= 2:
            genre_string = ''
            for value in genre:
                genre_string += value + ', '
            return genre_string[:-2]
        else:
            return genre
    display_genre.short_description = 'Genre'


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    short_biography = models.TextField(max_length=550, default='Write a little about the author')
    biography = models.TextField(max_length=10000, default='Write more about the author',
                                 help_text='Enter information about writer')
    photo = models.ImageField(upload_to='photo', blank=True, null=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Book, Author, Language, Genre


def index(request):
    """
    Display function for the site's home page.
    """

    # Get genres
    genres = ''
    for value in Genre.objects.all():
        genres += value.name + ', '
    genres = genres[:-2]

    # Get author's info
    author_data = Author.objects.all()

    # Get book's info
    book_data = Book.objects.all()

    # Number of visits to this view, as counted in the session variable.
    new_visits = request.session.get('new_visits', 0)
    request.session['new_visits'] = new_visits + 1

    context = {'author_data': author_data,
               'book_data': book_data,
               'new_visits': new_visits,
               'genre': Genre,
               }

    # Drawing an HTML template index.html with data inside
    # context variable
    return render(request, 'index.html', context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 12


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author


class UserFavoritesBooksListView(LoginRequiredMixin, generic.ListView):
    """
    A class-based view that shows the user's book favorites
    """
    model = Book
    template_name = 'catalog/favorite_user_books.html'
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.filter(favorites=self.request.user)


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'


class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'


class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')


class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = '__all__'


class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">

<head>
    {% block title %} <title>Library Home</title> {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>

    {% block sidebar %}
    <ul class="sidebar-nav">
        <div class="sidebar-nav-main"><a href="{% url 'index' %}">Главная</a></div>
        <hr class="sidebar-nav-line">
        <li><a href="{% url 'books' %}">Книги</a></li>
        <li><a href="{% url 'authors' %}">Авторы</a></li>
        <hr class="sidebar-nav-line">
        <li><a href="{% url 'my_favorites' %}">Избранные</a></li>
        <hr class="sidebar-nav-line">
        <li><a href="{% url 'book_create' %}">Добавить книгу</a></li>
        <li><a href="{% url 'author_create' %}">Добавить автора</a></li>
        <hr class="sidebar-nav-line">
        {% if user.is_authenticated %}
        <li><a href="">User: {{ user.get_username }}</a></li>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
    </ul>

    {% endblock %}

    <div class="main-content">
        {% block content %}{% endblock %}
        {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
                    {% endif %}
                    <span class="page-current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">вперед</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
        {% endblock %} 
    </div>

</body>

<script type="text/javascript" src="{% static 'js/script.js' %}" ></script>

</html>

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить автора</h1>

<p>Вы уверены, что хотите удалить автора: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да, удалить." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="author-info-full">

    <h1>{{ author.first_name }}, {{ author.last_name }}</h1>
    <h2>Об авторе</h2>

    <img src={{ author.photo.url }} alt="" style="float: left; margin: 0 10px 10px 0;">
    {{ author.biography }}

    <div>
        <a href="{% url 'author_update' author.id %}">Редактировать автора</a>
        <a href="{% url 'author_delete' author.id %}">Удалить автора</a>
    </div>

    <div class="author-info-full-book">
        <h1>Произведения автора</h1>
        {% for book in author.book_set.all %}
        <div>
            <a href="{% url 'book-detail' book.pk %}">{{ book }}</a>
            <p>{{ book.summary }}</p>
        </div>
        {% endfor%}
    </div>

</div>


{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список писателей</h1>

<div class="author-container">
    {% if author_list %}
            {% for author in author_list %}
                <div class="author-box">
                    {% if author.photo %}
                        <img class="author-photo" src="{{ author.photo.url }}">
                    {% else %}
                        <img class="author-photo "src="../../static/image/no_photo.png">
                    {% endif%}
                    <div class="author-info-right">
                        <h1 style="font-size: 18px;">{{ author.first_name }}, {{ author.last_name }}</h1>
                        <div>{{ author.short_biography }}... <a href="{{ author.get_absolute_url }}">Подробнее</a></div>
                    </div>
                </div>
            {% endfor %}
    {% else %}
        <p>no authors</p>
    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить книгу</h1>

<p>Вы уверены, что хотите удалить книгу: {{ book }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да, удалить." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ book.title }}</h1>

{% if book.image %}
    <div class="book-box-wrapper" style="background-image: url({{ book.image.url }}); background-size: cover;"><a href="{{ book.get_absolute_url }}" style="display: block; height: 100%;" ></a></div>
{% else %}
    <div class="book-box-wrapper"></div>
{% endif %}

<p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Описание книги:</strong> {{ book.summary }}</p>
<p><strong>Язык:</strong> {{ book.language }}</p>
<p><strong>Жарн:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><a href="{% url 'book_update' book.id %}">Редактировать</a></p>
<p><a href="{% url 'book_delete' book.id %}">Удалить</a></p>

{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}

    <div class="book-container">
        {% if book_list %}
            {% for book in book_list %}
            <div class="book-box-outer">
                {% if book.image %}
                    <div class="book-box-wrapper" style="background-image: url({{ book.image.url }}); background-size: cover;"><a href="{{ book.get_absolute_url }}" style="display: block; height: 100%;" ></a></div>
                    <div class="book-name">{{ book.title }}</div>
                {% else %}
                    <div class="book-box-wrapper"></div>
                    <div class="book-name"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></div>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
        <p>There are no books in the library.</p>
        {% endif %}
    </div>

{% endblock %}

catalog/templates/catalog/favorite_user_books.html
{% extends "base_generic.html" %}

{% block content %}

<div class="favorite">

    <h1>Мои избранные книги</h1>

    {% if book_list %}
        <ul>
            {% for book in book_list %}
            <div class="favorite-info">
                <li><a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a></li>
                <p>{{ book.summary }}</p>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p>Empty</p>
    {% endif %}

</div>

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Домашняя страница сайта</h1>
<p>Добро пожаловать на мой сайт сделанный с помощью python фреймворка - django</p>

<p>На этом сайте находится информация о разных книгах и их авторах</p>

<p><strong>Вы посетили эту страницу {{ new_visits }} раз</strong></p>
{% endblock %}